version: "3"
services:
  
  mysql:
    image: mysql:5.7
    ports:
      - "3308:3306"
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drivopsDB

volumes:
  mysqldb:   